# Nexus Réussite - Configuration Pre-commit
repos:
  # Hooks de base
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$|venv/|\.venv/|node_modules/'
      - id: end-of-file-fixer
        exclude: '\.md$|venv/|\.venv/|node_modules/'
      - id: check-yaml
        exclude: 'venv/|\.venv/|node_modules/'
      - id: check-json
        exclude: 'venv/|\.venv/|node_modules/|\.babelrc$|tsconfig\.json$'
      - id: check-merge-conflict
        exclude: 'venv/|\.venv/|node_modules/'

  # Python - Formatage Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^backend/src/
        exclude: 'venv/|\.venv/'
        language_version: python3

  # Python - Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^backend/src/
        exclude: 'venv/|\.venv/'
        args: ["--profile", "black"]

# Configuration globale
default_language_version:
  python: python3.12
