"""Initial migration with all models

Revision ID: a83ea12f3b78
Revises: 
Create Date: 2025-07-25 11:42:41.921614

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a83ea12f3b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_bricks',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('brick_type', sa.Enum('DEFINITION', 'THEOREME', 'PROPRIETE', 'EXEMPLE', 'EXERCICE', 'CORRECTION', 'CONSEIL_METHODE', 'HISTOIRE_SCIENCES', 'SCHEMA', 'FORMULE', name='bricktype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.Enum('MATHEMATIQUES', 'NSI', 'PHYSIQUE', 'CHIMIE', 'FRANCAIS', 'PHILOSOPHIE', 'HISTOIRE_GEO', 'SES', name='subject'), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('target_profiles', sa.JSON(), nullable=False),
    sa.Column('learning_steps', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('css_styles', sa.Text(), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_requests',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_profile', sa.Enum('STRUGGLING', 'AVERAGE', 'EXCELLENCE', 'REMEDIATION', name='targetprofile'), nullable=False),
    sa.Column('subject', sa.Enum('MATHEMATIQUES', 'NSI', 'PHYSIQUE', 'CHIMIE', 'FRANCAIS', 'PHILOSOPHIE', 'HISTOIRE_GEO', 'SES', name='subject'), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_min', sa.Integer(), nullable=False),
    sa.Column('difficulty_max', sa.Integer(), nullable=False),
    sa.Column('learning_step', sa.Enum('DISCOVERY', 'TRAINING', 'DEEPENING', 'REVISION', 'EVALUATION', name='learningstep'), nullable=False),
    sa.Column('duration_target', sa.Integer(), nullable=False),
    sa.Column('specific_topics', sa.JSON(), nullable=True),
    sa.Column('exclude_topics', sa.JSON(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('include_examples', sa.Boolean(), nullable=True),
    sa.Column('include_exercises', sa.Boolean(), nullable=True),
    sa.Column('include_corrections', sa.Boolean(), nullable=True),
    sa.Column('include_methods', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_brick_ratings',
    sa.Column('brick_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evaluator_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brick_id'], ['content_bricks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brick_id', 'user_id', name='unique_brick_rating')
    )
    op.create_table('generated_documents',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Float(), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('template_used', sa.String(length=100), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('student_rating', sa.Integer(), nullable=True),
    sa.Column('teacher_rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['document_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_bricks',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('brick_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brick_id'], ['content_bricks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['generated_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'brick_id', name='unique_document_brick')
    )
    op.create_table('document_interactions',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=30), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['generated_documents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    op.drop_table('document_interactions')
    op.drop_table('document_bricks')
    op.drop_table('generated_documents')
    op.drop_table('content_brick_ratings')
    op.drop_table('document_requests')
    op.drop_table('content_templates')
    op.drop_table('content_bricks')
    # ### end Alembic commands ###
