version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000/api/v1
      - NEXT_PUBLIC_WS_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - nexus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: nexus-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://nexus_user:nexus_password@db:5432/nexus_db
    depends_on:
      - db
    networks:
      - nexus-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=nexus_db
      - POSTGRES_USER=nexus_user
      - POSTGRES_PASSWORD=nexus_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexus-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - nexus-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  nexus-network:
    driver: bridge
